#import <Foundation/Foundation.h>
#import "SCObject.h"

/**
* Square Connect API
* No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

#import "SCAddress.h"


@protocol SCCard
@end

@interface SCCard : SCObject

/* The card's unique ID, if any. [optional]
 */
@property(nonatomic) NSString* _id;
/* The card's brand (such as `VISA`). [optional]
 */
@property(nonatomic) NSString* cardBrand;
/* The last 4 digits of the card's number. [optional]
 */
@property(nonatomic) NSString* last4;
/* The month of the card's expiration date, which must be between 1-12. [optional]
 */
@property(nonatomic) NSNumber* expMonth;
/* The year of the card's expiration date, which must be a 4-digit year. [optional]
 */
@property(nonatomic) NSNumber* expYear;
/* The cardholder name for the card on file. [optional]
 */
@property(nonatomic) NSString* cardholderName;
/* The billing address for the card on file. [optional]
 */
@property(nonatomic) SCAddress* billingAddress;

@end
