#import <Foundation/Foundation.h>
#import "SCObject.h"

/**
* Square Connect API
* No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

#import "SCAddress.h"


@protocol SCLocation
@end

@interface SCLocation : SCObject

/* The location's unique ID. [optional]
 */
@property(nonatomic) NSString* _id;
/* The name given to the location. [optional]
 */
@property(nonatomic) NSString* name;
/* The address of this location. [optional]
 */
@property(nonatomic) SCAddress* address;
/* The IANA Timezone Database identifier for the location's timezone. [optional]
 */
@property(nonatomic) NSString* timezone;
/* Indicates which Square features are enabled for the location.  Currently, there is only one value that might be present in this array: `CREDIT_CARD_PROCESSING`. [optional]
 */
@property(nonatomic) NSArray<NSString*>* capabilities;

@end
