#import <Foundation/Foundation.h>
#import "SCObject.h"

/**
* Square Connect API
* No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

#import "SCMoney.h"
#import "SCTenderCardDetails.h"
#import "SCTenderCashDetails.h"


@protocol SCTender
@end

@interface SCTender : SCObject

/* The tender's unique ID. [optional]
 */
@property(nonatomic) NSString* _id;
/* The ID of the tender's associated location. [optional]
 */
@property(nonatomic) NSString* locationId;
/* The ID of the tender's associated transaction. [optional]
 */
@property(nonatomic) NSString* transactionId;
/* The time when the tender was created, in RFC 3339 format. [optional]
 */
@property(nonatomic) NSString* createdAt;
/* An optional note associated with the tender at the time of payment. [optional]
 */
@property(nonatomic) NSString* note;
/* The amount of the tender. [optional]
 */
@property(nonatomic) SCMoney* amountMoney;
/* The amount of any Square processing fees applied to the tender. [optional]
 */
@property(nonatomic) SCMoney* processingFeeMoney;
/* If the tender represents a customer's card on file, this is the ID of the associated customer. [optional]
 */
@property(nonatomic) NSString* customerId;
/* The type of tender. 
 */
@property(nonatomic) NSString* type;
/* The details of the card tender. This value is present only if the value of `type` is `CARD`. [optional]
 */
@property(nonatomic) SCTenderCardDetails* cardDetails;
/* The details of the cash tender. This value is present only if the value of `type` is `CASH`. [optional]
 */
@property(nonatomic) SCTenderCashDetails* cashDetails;

@end
