#import <Foundation/Foundation.h>
#import "SQCObject.h"

/**
* Square Connect API
* No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

#import "SQCError.h"
#import "SQCTransaction.h"


@protocol SQCListTransactionsResponse
@end

@interface SQCListTransactionsResponse : SQCObject

/* Any errors that occurred during the request. [optional]
 */
@property(nonatomic) NSArray<SQCError>* errors;
/* An array of transactions that match your query. [optional]
 */
@property(nonatomic) NSArray<SQCTransaction>* transactions;
/* A pagination cursor for retrieving the next set of results, if any remain.  Provide this value as the `cursor` parameter in a subsequent request to the **ListTransactions** endpoint. [optional]
 */
@property(nonatomic) NSString* cursor;

@end
