#import <Foundation/Foundation.h>
#import "SQCObject.h"

/**
* Square Connect API
* No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

#import "SQCMoney.h"


@protocol SQCRefund
@end

@interface SQCRefund : SQCObject

/* The unique ID of the refund. 
 */
@property(nonatomic) NSString* _id;
/* The ID of the refund's associated location. 
 */
@property(nonatomic) NSString* locationId;
/* The ID of the transaction refunded. 
 */
@property(nonatomic) NSString* transactionId;
/* The ID of the tender refunded. 
 */
@property(nonatomic) NSString* tenderId;
/* The time when the refund was created, in RFC 3339 format. [optional]
 */
@property(nonatomic) NSString* createdAt;
/* The reason for the refund being issued. 
 */
@property(nonatomic) NSString* reason;
/* The amount of money refunded. 
 */
@property(nonatomic) SQCMoney* amountMoney;
/*  
 */
@property(nonatomic) NSString* status;
/* The amount of processing fee refunded. [optional]
 */
@property(nonatomic) SQCMoney* processingFeeMoney;

@end
