#import <Foundation/Foundation.h>
#import "SQCObject.h"

/**
* Square Connect API
* No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

#import "SQCRefund.h"
#import "SQCTender.h"


@protocol SQCTransaction
@end

@interface SQCTransaction : SQCObject

/* The transaction's unique ID. [optional]
 */
@property(nonatomic) NSString* _id;
/* The ID of the transaction's associated location. [optional]
 */
@property(nonatomic) NSString* locationId;
/* The time when the transaction was created, in RFC 3339 format. [optional]
 */
@property(nonatomic) NSString* createdAt;
/* Descriptions of the tenders used to pay for the transaction. [optional]
 */
@property(nonatomic) NSArray<SQCTender>* tenders;
/* An array of any refunds associated with the transaction. [optional]
 */
@property(nonatomic) NSArray<SQCRefund>* refunds;
/* If the transaction was created with the **Charge** endpoint, this value is the same as the value provided as the `reference_id` parameter in the request to that endpoint. [optional]
 */
@property(nonatomic) NSString* referenceId;
/* The product that processed the transaction. [optional]
 */
@property(nonatomic) NSString* product;

@end
