#import <Foundation/Foundation.h>
#import "SCCreateCustomerRequest.h"
#import "SCCreateCustomerResponse.h"
#import "SCDeleteCustomerResponse.h"
#import "SCListCustomersResponse.h"
#import "SCRetrieveCustomerResponse.h"
#import "SCUpdateCustomerResponse.h"
#import "SCUpdateCustomerRequest.h"
#import "SCApi.h"

/**
* Square Connect API
* No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


@interface SCCustomerApi: NSObject <SCApi>

extern NSString* kSCCustomerApiErrorDomain;
extern NSInteger kSCCustomerApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// CreateCustomer
/// Creates a new customer for the business, which can have associated cards on file.
///
/// @param authorization The value to provide in the Authorization header of your request. This value should follow the format &#x60;Bearer YOUR_ACCESS_TOKEN_HERE&#x60;.
/// @param body An object containing the fields to POST for the request.  See the corresponding object definition for field details.
/// 
///  code:200 message:"Success"
///
/// @return SCCreateCustomerResponse*
-(NSNumber*) createCustomerWithAuthorization: (NSString*) authorization
    body: (SCCreateCustomerRequest*) body
    completionHandler: (void (^)(SCCreateCustomerResponse* output, NSError* error)) handler;


/// DeleteCustomer
/// Deletes a customer from a business.
///
/// @param authorization The value to provide in the Authorization header of your request. This value should follow the format &#x60;Bearer YOUR_ACCESS_TOKEN_HERE&#x60;.
/// @param customerId 
/// 
///  code:200 message:"Success"
///
/// @return SCDeleteCustomerResponse*
-(NSNumber*) deleteCustomerWithAuthorization: (NSString*) authorization
    customerId: (NSString*) customerId
    completionHandler: (void (^)(SCDeleteCustomerResponse* output, NSError* error)) handler;


/// ListCustomers
/// Lists a business's customers.
///
/// @param authorization The value to provide in the Authorization header of your request. This value should follow the format &#x60;Bearer YOUR_ACCESS_TOKEN_HERE&#x60;.
/// @param cursor  (optional)
/// 
///  code:200 message:"Success"
///
/// @return SCListCustomersResponse*
-(NSNumber*) listCustomersWithAuthorization: (NSString*) authorization
    cursor: (NSString*) cursor
    completionHandler: (void (^)(SCListCustomersResponse* output, NSError* error)) handler;


/// RetrieveCustomer
/// Returns details for a single customer.
///
/// @param authorization The value to provide in the Authorization header of your request. This value should follow the format &#x60;Bearer YOUR_ACCESS_TOKEN_HERE&#x60;.
/// @param customerId 
/// 
///  code:200 message:"Success"
///
/// @return SCRetrieveCustomerResponse*
-(NSNumber*) retrieveCustomerWithAuthorization: (NSString*) authorization
    customerId: (NSString*) customerId
    completionHandler: (void (^)(SCRetrieveCustomerResponse* output, NSError* error)) handler;


/// UpdateCustomer
/// Updates the details of an existing customer.
///
/// @param authorization The value to provide in the Authorization header of your request. This value should follow the format &#x60;Bearer YOUR_ACCESS_TOKEN_HERE&#x60;.
/// @param customerId The customer to update.
/// @param body An object containing the fields to POST for the request.  See the corresponding object definition for field details.
/// 
///  code:200 message:"Success"
///
/// @return SCUpdateCustomerResponse*
-(NSNumber*) updateCustomerWithAuthorization: (NSString*) authorization
    customerId: (NSString*) customerId
    body: (SCUpdateCustomerRequest*) body
    completionHandler: (void (^)(SCUpdateCustomerResponse* output, NSError* error)) handler;



@end
