#import <Foundation/Foundation.h>
#import "SCCreateRefundRequest.h"
#import "SCCreateRefundResponse.h"
#import "SCListRefundsResponse.h"
#import "SCApi.h"

/**
* Square Connect API
* No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


@interface SCRefundApi: NSObject <SCApi>

extern NSString* kSCRefundApiErrorDomain;
extern NSInteger kSCRefundApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// CreateRefund
/// Initiates a refund for a previously charged tender.
///
/// @param authorization The value to provide in the Authorization header of your request. This value should follow the format &#x60;Bearer YOUR_ACCESS_TOKEN_HERE&#x60;.
/// @param locationId The ID of the original transaction&#39;s associated location.
/// @param transactionId 
/// @param body An object containing the fields to POST for the request.  See the corresponding object definition for field details.
/// 
///  code:200 message:"Success"
///
/// @return SCCreateRefundResponse*
-(NSNumber*) createRefundWithAuthorization: (NSString*) authorization
    locationId: (NSString*) locationId
    transactionId: (NSString*) transactionId
    body: (SCCreateRefundRequest*) body
    completionHandler: (void (^)(SCCreateRefundResponse* output, NSError* error)) handler;


/// ListRefunds
/// Lists refunds for one of a business's locations.
///
/// @param authorization The value to provide in the Authorization header of your request. This value should follow the format &#x60;Bearer YOUR_ACCESS_TOKEN_HERE&#x60;.
/// @param locationId The ID of the location to list refunds for.
/// @param beginTime The beginning of the requested reporting period, in RFC 3339 format. (optional)
/// @param endTime The end of the requested reporting period, in RFC 3339 format. (optional)
/// @param sortOrder The order in which results are listed in the response. (optional)
/// @param cursor A pagination cursor to retrieve the next set of results for your original query to the endpoint. (optional)
/// 
///  code:200 message:"Success"
///
/// @return SCListRefundsResponse*
-(NSNumber*) listRefundsWithAuthorization: (NSString*) authorization
    locationId: (NSString*) locationId
    beginTime: (NSString*) beginTime
    endTime: (NSString*) endTime
    sortOrder: (NSString*) sortOrder
    cursor: (NSString*) cursor
    completionHandler: (void (^)(SCListRefundsResponse* output, NSError* error)) handler;



@end
