#import <Foundation/Foundation.h>
#import "SQCCreateCustomerRequest.h"
#import "SQCCreateCustomerResponse.h"
#import "SQCDeleteCustomerResponse.h"
#import "SQCListCustomersResponse.h"
#import "SQCRetrieveCustomerResponse.h"
#import "SQCUpdateCustomerResponse.h"
#import "SQCUpdateCustomerRequest.h"
#import "SQCApi.h"

/**
* Square Connect API
* No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


@interface SQCCustomerApi: NSObject <SQCApi>

extern NSString* kSQCCustomerApiErrorDomain;
extern NSInteger kSQCCustomerApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// CreateCustomer
/// Creates a new customer for the business, which can have associated cards on file.
///
/// @param authorization The value to provide in the Authorization header of your request. This value should follow the format &#x60;Bearer YOUR_ACCESS_TOKEN_HERE&#x60;.
/// @param body An object containing the fields to POST for the request.  See the corresponding object definition for field details.
/// 
///  code:200 message:"Success"
///
/// @return SQCCreateCustomerResponse*
-(NSNumber*) createCustomerWithAuthorization: (NSString*) authorization
    body: (SQCCreateCustomerRequest*) body
    completionHandler: (void (^)(SQCCreateCustomerResponse* output, NSError* error)) handler;


/// DeleteCustomer
/// Deletes a customer from a business.
///
/// @param authorization The value to provide in the Authorization header of your request. This value should follow the format &#x60;Bearer YOUR_ACCESS_TOKEN_HERE&#x60;.
/// @param customerId 
/// 
///  code:200 message:"Success"
///
/// @return SQCDeleteCustomerResponse*
-(NSNumber*) deleteCustomerWithAuthorization: (NSString*) authorization
    customerId: (NSString*) customerId
    completionHandler: (void (^)(SQCDeleteCustomerResponse* output, NSError* error)) handler;


/// ListCustomers
/// Lists a business's customers.
///
/// @param authorization The value to provide in the Authorization header of your request. This value should follow the format &#x60;Bearer YOUR_ACCESS_TOKEN_HERE&#x60;.
/// @param cursor  (optional)
/// 
///  code:200 message:"Success"
///
/// @return SQCListCustomersResponse*
-(NSNumber*) listCustomersWithAuthorization: (NSString*) authorization
    cursor: (NSString*) cursor
    completionHandler: (void (^)(SQCListCustomersResponse* output, NSError* error)) handler;


/// RetrieveCustomer
/// Returns details for a single customer.
///
/// @param authorization The value to provide in the Authorization header of your request. This value should follow the format &#x60;Bearer YOUR_ACCESS_TOKEN_HERE&#x60;.
/// @param customerId 
/// 
///  code:200 message:"Success"
///
/// @return SQCRetrieveCustomerResponse*
-(NSNumber*) retrieveCustomerWithAuthorization: (NSString*) authorization
    customerId: (NSString*) customerId
    completionHandler: (void (^)(SQCRetrieveCustomerResponse* output, NSError* error)) handler;


/// UpdateCustomer
/// Updates the details of an existing customer.
///
/// @param authorization The value to provide in the Authorization header of your request. This value should follow the format &#x60;Bearer YOUR_ACCESS_TOKEN_HERE&#x60;.
/// @param customerId The customer to update.
/// @param body An object containing the fields to POST for the request.  See the corresponding object definition for field details.
/// 
///  code:200 message:"Success"
///
/// @return SQCUpdateCustomerResponse*
-(NSNumber*) updateCustomerWithAuthorization: (NSString*) authorization
    customerId: (NSString*) customerId
    body: (SQCUpdateCustomerRequest*) body
    completionHandler: (void (^)(SQCUpdateCustomerResponse* output, NSError* error)) handler;



@end
