#import <Foundation/Foundation.h>
#import "SQCListLocationsResponse.h"
#import "SQCApi.h"

/**
* Square Connect API
* No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


@interface SQCLocationApi: NSObject <SQCApi>

extern NSString* kSQCLocationApiErrorDomain;
extern NSInteger kSQCLocationApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// ListLocations
/// Provides summary information for all of a business's locations.
///
/// @param authorization The value to provide in the Authorization header of your request. This value should follow the format &#x60;Bearer YOUR_ACCESS_TOKEN_HERE&#x60;.
/// 
///  code:200 message:"Success"
///
/// @return SQCListLocationsResponse*
-(NSNumber*) listLocationsWithAuthorization: (NSString*) authorization
    completionHandler: (void (^)(SQCListLocationsResponse* output, NSError* error)) handler;



@end
